"""User-approved permanent identity exclusions for research universes.

Keep this policy outside the frozen PIT authority: it is an explicit,
downstream universe rule and must not rewrite authoritative source records.
Callers should apply it once while constructing the shared universe, before
splitting observations into strategy/control populations.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any


PERMANENT_IDENTITY_EXCLUSIONS: dict[tuple[str, str], dict[str, str]] = {
    ("010420", "KR7010420008"): {
        "reason": "user-approved permanent exclusion for the 2025-09-25 delisting / wholly owned subsidiary lifecycle",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("005390", "KR7005390000"): {
        "reason": "user-approved permanent exclusion for a rare lifecycle identity in the P3-2 audit roster",
        "approval_scope": "P3-2 recertification V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("006390", "KR7006390009"): {
        "reason": "user-approved permanent exclusion for a rare lifecycle identity in the P3-2 audit roster",
        "approval_scope": "P3-2 recertification V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("031440", "KR7031440001"): {
        "reason": "user-approved permanent exclusion for a rare lifecycle identity in the P3-2 audit roster",
        "approval_scope": "P3-2 recertification V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("049770", "KR7049770001"): {
        "reason": "user-approved permanent exclusion for a rare lifecycle identity in the P3-2 audit roster",
        "approval_scope": "P3-2 recertification V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("057050", "KR7057050007"): {
        "reason": "user-approved permanent exclusion for a rare lifecycle identity in the P3-2 audit roster",
        "approval_scope": "P3-2 recertification V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("138490", "KR7138490008"): {
        "reason": "user-approved permanent exclusion for a rare lifecycle identity in the P3-2 audit roster",
        "approval_scope": "P3-2 recertification V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("335890", "KR7335890000"): {
        "reason": "user-approved permanent exclusion for a rare lifecycle identity in the P3-2 audit roster",
        "approval_scope": "P3-2 recertification V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("950110", "KR8392070007"): {
        "reason": "user-approved permanent exclusion for a rare lifecycle identity in the P3-2 audit roster",
        "approval_scope": "P3-2 recertification V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("069460", "KR7069460004"): {
        "reason": "user-approved permanent exclusion because authoritative terminal pricing is unavailable through the P3-2 cutoff",
        "approval_scope": "P3-2 final closure V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("246720", "KR7246720007"): {
        "reason": "user-approved permanent exclusion because authoritative terminal pricing is unavailable through the P3-2 cutoff",
        "approval_scope": "P3-2 final closure V01",
        "approved_date": "2026-09-25",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("001140", "KR7001140003"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("009730", "KR7009730003"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by an empty resampler week bucket",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "A_PIPELINE_BUG",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("031980", "KR7031980006"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("035290", "KR7035290006"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("036260", "KR7036260008"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("036620", "KR7036620003"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by an empty resampler week bucket",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "A_PIPELINE_BUG",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("043710", "KR7043710003"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("044060", "KR7044060002"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("052300", "KR7052300001"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by an empty resampler week bucket",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "A_PIPELINE_BUG",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("052400", "KR7052400009"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("068150", "KR7068150002"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("130660", "KR7130660004"): {
        "reason": "user-approved permanent exclusion for P1 Pattern A stage UNAVAILABLE caused by Repository V2 source gaps",
        "approval_scope": "P1 UNAVAILABLE 12 permanent exclusion V01",
        "failure_class": "C_SOURCE_OR_AUTHORITY_GAP",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("005950", "KR7005950001"): {
        "reason": "user-approved permanent exclusion after a P1 soft-exit next-session execution contract mismatch",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_EXECUTION_ANOMALY",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002250", "KR7002250009"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002270", "KR7002270007"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002550", "KR7002550002"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003450", "KR7003450004"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003600", "KR7003600004"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("005190", "KR7005190004"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("008020", "KR7008020000"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("008720", "KR7008720005"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("013450", "KR7013450002"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("016170", "KR7016170003"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("019680", "KR7019680008"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("020760", "KR7020760005"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("031860", "KR7031860000"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("032980", "KR7032980005"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("033630", "KR7033630005"): {
        "reason": "user-approved permanent exclusion for a delisted P1 identity with an unexecuted signal and lifecycle gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("033660", "KR7033660002"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("043220", "KR7043220003"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("123100", "KR7123100000"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("130960", "KR7130960008"): {
        "reason": "user-approved permanent exclusion after a P1 lifecycle remediable-unresolved gate finding",
        "approval_scope": "P1 final exclusion closure V02",
        "failure_class": "P1_LIFECYCLE_REMEDIABLE_UNRESOLVED",
        "approved_date": "2026-09-26",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("000100", "KR7000100008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("000210", "KR7000210005"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("000220", "KR7000220004"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("000370", "KR7000370007"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("000440", "KR7000440008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("000480", "KR7000480004"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("001060", "KR7001060003"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("001070", "KR7001070002"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("001540", "KR7001540004"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("001790", "KR7001790005"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002240", "KR7002240000"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002320", "KR7002320000"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002420", "KR7002420008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002720", "KR7002720001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002790", "KR7002790004"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002840", "KR7002840007"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("002900", "KR7002900009"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003000", "KR7003000007"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003120", "KR7003120003"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003220", "KR7003220001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003300", "KR7003300001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003490", "KR7003490000"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003550", "KR7003550001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003670", "KR7003670007"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("003920", "KR7003920006"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("004140", "KR7004140000"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("004800", "KR7004800009"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("004990", "KR7004990008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("005420", "KR7005420005"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("005440", "KR7005440003"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("005880", "KR7005880000"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("005930", "KR7005930003"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("005990", "KR7005990007"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("006220", "KR7006220008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("006400", "KR7006400006"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("006730", "KR7006730006"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("007340", "KR7007340003"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("007390", "KR7007390008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("007690", "KR7007690001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("008060", "KR7008060006"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("009180", "KR7009180001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("010060", "KR7010060002"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("011170", "KR7011170008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("012320", "KR7012320008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("013520", "KR7013520002"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("017670", "KR7017670001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("018500", "KR7018500009"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("020150", "KR7020150009"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("025880", "KR7025880006"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("028300", "KR7028300002"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("032560", "KR7032560005"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("033290", "KR7033290008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("036480", "KR7036480002"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("038540", "KR7038540001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("045970", "KR7045970001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("051630", "KR7051630002"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("067570", "KR7067570002"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("069140", "KR7069140002"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("070300", "KR7070300009"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("088980", "KR7088980008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("099190", "KR7099190001"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("099320", "KR7099320004"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("119850", "KR7119850006"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("138070", "KR7138070008"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("181710", "KR7181710005"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },
    ("900140", "KYG5307W1015"): {
        "reason": "user-approved permanent exclusion for unresolved Repository V2 daily valuation RAW_DATA_GAP",
        "approval_scope": "V2 official adoption MDD closure 2026-09-28",
        "failure_class": "MDD_RAW_DATA_GAP",
        "approved_date": "2026-09-28",
        "policy_version": "permanent_identity_exclusions_v01",
    },

}


def apply_permanent_identity_exclusions(
    segments: Iterable[Any],
) -> tuple[list[Any], list[dict[str, str]]]:
    """Return kept segments and an auditable record for each removed interval.

    Matching requires both ticker and stable ISU code, so a later ticker reuse
    for a different security identity is not excluded by this policy.
    """
    kept: list[Any] = []
    excluded: list[dict[str, str]] = []
    for segment in segments:
        ticker = str(getattr(segment, "ticker", "")).strip().zfill(6)
        isu_cd = str(getattr(segment, "isu_cd", "")).strip().upper()
        policy = PERMANENT_IDENTITY_EXCLUSIONS.get((ticker, isu_cd))
        if policy is None:
            kept.append(segment)
            continue
        excluded.append(
            {
                "ticker": ticker,
                "isu_cd": isu_cd,
                "market": str(getattr(segment, "market", "")),
                "effective_from": str(getattr(segment, "effective_from", ""))[:10],
                "effective_to": str(getattr(segment, "effective_to", ""))[:10],
                **policy,
            }
        )
    return kept, excluded
