"""Offline full trade-level parity runner for A FAST Core V2.

The frozen V02 trade CSV is treated as read-only authority.  Production rows
are generated by invoking the current simulator over the same local source and
then compared independently, field by field, after CSV round-trip parsing.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor
from contextlib import contextmanager
from decimal import Decimal, InvalidOperation
import hashlib
import json
from pathlib import Path
import socket
import subprocess
import time
from typing import Any, Iterator
import warnings

import numpy as np
import pandas as pd

from trend_scanner.data.cache import ParquetCache
from trend_scanner.validation.pattern_a_fast_core_v02_reentry import (
    DATA_CUTOFF,
    simulate_ticker_core_v02_reentry,
)

warnings.filterwarnings("ignore")

AS_OF = "2026-08-14"
START_HEAD = "207dc6e43d90aabdd0e06eb394c17f34cc689922"
START_TREE = "b109dca8513c0b34d967dcda104194bb8c57d5a8"
EXPECTED_COUNTS = {
    "total_trades": 783,
    "first_entries": 551,
    "reentry_trades": 232,
    "unique_tickers": 551,
    "reentered_tickers": 151,
}

TRADE_COLUMNS = [
    "ticker", "name", "market", "trade_id", "trade_sequence",
    "entry_signal_date", "entry_execution_date", "entry_open",
    "entry_pattern_a_stage", "fast_stage", "monthly_regime", "daily_risk",
    "fast_score", "fast_score_state", "previous_exit_type",
    "previous_exit_execution_date", "loss_guard_triggered", "loss_guard_signal_date",
    "loss_guard_execution_date", "loss_guard_execution_price", "first_progressed_date",
    "first_progressed_effective_trading_date", "lifecycle_class", "exit_type",
    "exit_signal_date", "exit_execution_date", "exit_price", "terminal_return",
    "mfe", "mae", "peak_giveback", "profit_capture", "holding_weeks", "trade_status",
]
STRUCTURAL_COLUMNS = [
    "ticker", "name", "market", "trade_id", "trade_sequence",
    "entry_signal_date", "entry_execution_date", "entry_pattern_a_stage", "fast_stage",
    "monthly_regime", "daily_risk", "fast_score_state", "previous_exit_type",
    "previous_exit_execution_date", "loss_guard_triggered", "loss_guard_signal_date",
    "loss_guard_execution_date", "first_progressed_date",
    "first_progressed_effective_trading_date", "lifecycle_class", "exit_type",
    "exit_signal_date", "exit_execution_date", "trade_status",
]
NUMERIC_COLUMNS = [
    "entry_open", "fast_score", "loss_guard_execution_price", "exit_price",
    "terminal_return", "mfe", "mae", "peak_giveback", "profit_capture", "holding_weeks",
]


class NetworkRequestBlocked(RuntimeError):
    pass


class NetworkAudit:
    def __init__(self) -> None:
        self.request_count = 0


@contextmanager
def network_guard(audit: NetworkAudit) -> Iterator[None]:
    """Fail closed if production code accidentally opens an outbound socket."""
    original_connect = socket.socket.connect
    original_connect_ex = socket.socket.connect_ex

    def blocked_connect(self: socket.socket, address: Any) -> None:
        audit.request_count += 1
        raise NetworkRequestBlocked(f"offline FASTCORE guard blocked socket connect: {address!r}")

    def blocked_connect_ex(self: socket.socket, address: Any) -> int:
        audit.request_count += 1
        raise NetworkRequestBlocked(f"offline FASTCORE guard blocked socket connect_ex: {address!r}")

    socket.socket.connect = blocked_connect  # type: ignore[method-assign]
    socket.socket.connect_ex = blocked_connect_ex  # type: ignore[method-assign]
    try:
        yield
    finally:
        socket.socket.connect = original_connect  # type: ignore[method-assign]
        socket.socket.connect_ex = original_connect_ex  # type: ignore[method-assign]


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def git_blob_sha(repo_root: Path, revision: str, relative_path: str) -> str:
    result = subprocess.run(
        ["git", "show", f"{revision}:{relative_path}"],
        cwd=repo_root,
        check=True,
        capture_output=True,
    )
    return sha256_bytes(result.stdout)


def _worker(args: tuple[str, str, str, dict, dict]) -> list[dict[str, Any]]:
    ticker, name, market, score_contract, stage_contract = args
    root = Path(__file__).resolve().parents[1]
    daily = ParquetCache(base_dir=root / "data/raw/stocks").load(ticker)
    records = simulate_ticker_core_v02_reentry(
        ticker=ticker,
        name=name,
        market=market,
        daily=daily,
        score_contract=score_contract,
        stage_contract=stage_contract,
        cutoff_date=DATA_CUTOFF,
    )
    return [record.to_dict() for record in records]


def load_investable_universe(repo_root: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    path = repo_root / "artifacts/patterns/pattern_a/production/investability/pattern_a_investability_universe_20260814.csv"
    universe = pd.read_csv(path, dtype={"ticker": str})
    universe["ticker"] = universe["ticker"].astype(str).str.zfill(6)
    investable_mask = (
        (universe["market_cap_ready"] == True)
        & (universe["trading_value_20d_ready"] == True)
        & (universe["market_cap"] >= 100_000_000_000)
        & (universe["avg_trading_value_20d"] >= 300_000_000)
    )
    investable = universe.loc[investable_mask].copy().sort_values("ticker", kind="mergesort").reset_index(drop=True)
    return universe, investable


def run_production(repo_root: Path, output_root: Path, audit: NetworkAudit) -> tuple[pd.DataFrame, float]:
    score_contract = json.loads((repo_root / "artifacts/patterns/pattern_a_fast/production/contract_prototype/pattern_a_fast_score_prototype_v01.json").read_text(encoding="utf-8"))
    stage_contract = json.loads((repo_root / "artifacts/patterns/pattern_a_fast/production/contract_prototype/pattern_a_fast_stage_prototype_v01.json").read_text(encoding="utf-8"))
    universe, investable = load_investable_universe(repo_root)
    tasks = [
        (str(row.ticker).zfill(6), str(row.name), str(row.market), score_contract, stage_contract)
        for row in investable.itertuples(index=False)
    ]
    started = time.monotonic()
    with network_guard(audit):
        with ProcessPoolExecutor(max_workers=8) as executor:
            nested = list(executor.map(_worker, tasks))
    rows = [row for group in nested for row in group]
    production = pd.DataFrame(rows, columns=TRADE_COLUMNS)
    if production.empty:
        production = pd.DataFrame(columns=TRADE_COLUMNS)
    production["ticker"] = production["ticker"].astype(str).str.zfill(6)
    production["trade_sequence"] = production["trade_sequence"].astype("Int64")
    production = production.sort_values(["ticker", "trade_sequence"], kind="mergesort").reset_index(drop=True)
    output_root.mkdir(parents=True, exist_ok=True)
    for subdir in ("authority", "dependencies", "production", "parity", "distributions", "reentry", "canaries", "metrics", "validation", "final"):
        (output_root / subdir).mkdir(parents=True, exist_ok=True)
    production.to_csv(output_root / "production/production_fastcore_trades_20260814.csv", index=False)
    return production, time.monotonic() - started


def _null(value: Any) -> bool:
    try:
        return bool(pd.isna(value))
    except (TypeError, ValueError):
        return value is None


def canonical(value: Any, column: str) -> str:
    if _null(value) or value == "":
        return "<NULL>"
    if column in NUMERIC_COLUMNS:
        try:
            return str(Decimal(str(value)))
        except (InvalidOperation, ValueError):
            return f"<INVALID:{value}>"
    if column == "loss_guard_triggered":
        return str(value).strip().lower()
    if column == "trade_sequence":
        return str(int(value))
    if column.endswith("date") or column.endswith("_date"):
        try:
            return pd.Timestamp(value).strftime("%Y-%m-%d")
        except (TypeError, ValueError):
            pass
    return str(value)


def _prepare(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    missing = [column for column in TRADE_COLUMNS if column not in out.columns]
    if missing:
        raise ValueError(f"required columns missing: {missing}")
    out["ticker"] = out["ticker"].astype(str).str.zfill(6)
    out["trade_sequence"] = pd.to_numeric(out["trade_sequence"], errors="coerce")
    return out[TRADE_COLUMNS]


def compare_trades(authority: pd.DataFrame, production: pd.DataFrame) -> dict[str, Any]:
    authority = _prepare(authority)
    production = _prepare(production)
    auth_keys = {(canonical(row.ticker, "ticker"), canonical(row.trade_sequence, "trade_sequence")) for row in authority.itertuples()}
    prod_keys = {(canonical(row.ticker, "ticker"), canonical(row.trade_sequence, "trade_sequence")) for row in production.itertuples()}
    missing = sorted(auth_keys - prod_keys)
    extra = sorted(prod_keys - auth_keys)
    auth_ids = {canonical(value, "trade_id") for value in authority["trade_id"]}
    prod_ids = {canonical(value, "trade_id") for value in production["trade_id"]}
    duplicate_key_count = int(authority.duplicated(["ticker", "trade_sequence"]).sum() + production.duplicated(["ticker", "trade_sequence"]).sum())
    duplicate_trade_id_count = int(authority["trade_id"].duplicated().sum() + production["trade_id"].duplicated().sum())
    mismatches: list[dict[str, Any]] = []
    structural_count = 0
    numeric_count = 0
    max_error = 0.0
    auth_index = {(canonical(row.ticker, "ticker"), canonical(row.trade_sequence, "trade_sequence")): row for row in authority.itertuples()}
    prod_index = {(canonical(row.ticker, "ticker"), canonical(row.trade_sequence, "trade_sequence")): row for row in production.itertuples()}
    for key in sorted(auth_keys & prod_keys):
        left, right = auth_index[key], prod_index[key]
        for column in STRUCTURAL_COLUMNS:
            a, b = canonical(getattr(left, column), column), canonical(getattr(right, column), column)
            if a != b:
                structural_count += 1
                if len(mismatches) < 100:
                    mismatches.append({"ticker": key[0], "trade_sequence": key[1], "column": column, "authority": a, "production": b, "kind": "STRUCTURAL"})
        for column in NUMERIC_COLUMNS:
            a, b = canonical(getattr(left, column), column), canonical(getattr(right, column), column)
            if a == b:
                continue
            numeric_count += 1
            try:
                max_error = max(max_error, abs(float(Decimal(a) - Decimal(b))))
            except (InvalidOperation, ValueError):
                max_error = float("inf")
            if len(mismatches) < 100:
                mismatches.append({"ticker": key[0], "trade_sequence": key[1], "column": column, "authority": a, "production": b, "kind": "NUMERIC"})
    return {
        "authority_trades": len(authority), "production_trades": len(production),
        "missing_trades": len(missing), "extra_trades": len(extra),
        "missing_trade_keys": missing[:100], "extra_trade_keys": extra[:100],
        "duplicate_row_keys": duplicate_key_count, "duplicate_trade_ids": duplicate_trade_id_count,
        "trade_id_set_missing": len(auth_ids - prod_ids), "trade_id_set_extra": len(prod_ids - auth_ids),
        "structural_mismatches": structural_count, "numeric_mismatches": numeric_count,
        "max_numeric_abs_error": max_error, "mismatches": mismatches,
    }


def trade_level_parity_rows(authority: pd.DataFrame, production: pd.DataFrame) -> pd.DataFrame:
    """Return one explicit pass/fail row for every authority/production trade key."""
    authority = _prepare(authority)
    production = _prepare(production)
    auth_index = {
        (canonical(row.ticker, "ticker"), canonical(row.trade_sequence, "trade_sequence")): row
        for row in authority.itertuples()
    }
    prod_index = {
        (canonical(row.ticker, "ticker"), canonical(row.trade_sequence, "trade_sequence")): row
        for row in production.itertuples()
    }
    rows: list[dict[str, Any]] = []
    for key in sorted(set(auth_index) | set(prod_index)):
        left, right = auth_index.get(key), prod_index.get(key)
        structural_mismatch_count = 0
        numeric_mismatch_count = 0
        max_numeric_abs_error = 0.0
        if left is None or right is None:
            structural_mismatch_count = len(STRUCTURAL_COLUMNS)
            numeric_mismatch_count = len(NUMERIC_COLUMNS)
        else:
            for column in STRUCTURAL_COLUMNS:
                structural_mismatch_count += int(
                    canonical(getattr(left, column), column)
                    != canonical(getattr(right, column), column)
                )
            for column in NUMERIC_COLUMNS:
                a = canonical(getattr(left, column), column)
                b = canonical(getattr(right, column), column)
                if a == b:
                    continue
                numeric_mismatch_count += 1
                try:
                    max_numeric_abs_error = max(
                        max_numeric_abs_error, abs(float(Decimal(a) - Decimal(b)))
                    )
                except (InvalidOperation, ValueError):
                    max_numeric_abs_error = float("inf")
        trade_id = (
            canonical(getattr(left, "trade_id"), "trade_id")
            if left is not None
            else canonical(getattr(right, "trade_id"), "trade_id")
        )
        rows.append(
            {
                "ticker": key[0],
                "trade_sequence": key[1],
                "trade_id": trade_id,
                "structural_match": structural_mismatch_count == 0,
                "numeric_match": numeric_mismatch_count == 0,
                "overall_match": structural_mismatch_count == 0 and numeric_mismatch_count == 0,
                "structural_mismatch_count": structural_mismatch_count,
                "numeric_mismatch_count": numeric_mismatch_count,
                "max_numeric_abs_error": max_numeric_abs_error,
            }
        )
    return pd.DataFrame(
        rows,
        columns=[
            "ticker", "trade_sequence", "trade_id", "structural_match", "numeric_match",
            "overall_match", "structural_mismatch_count", "numeric_mismatch_count",
            "max_numeric_abs_error",
        ],
    )


def distribution(df: pd.DataFrame, column: str) -> dict[str, int]:
    return {canonical(key, column): int(value) for key, value in df[column].value_counts(dropna=False).items()}


def distribution_parity(authority: pd.DataFrame, production: pd.DataFrame) -> dict[str, Any]:
    fields = ["exit_type", "trade_status", "lifecycle_class", "loss_guard_triggered", "trade_sequence", "entry_pattern_a_stage", "monthly_regime", "daily_risk", "fast_score_state", "market"]
    result = {}
    mismatches = 0
    for field in fields:
        a, p = distribution(authority, field), distribution(production, field)
        result[field] = {"authority": a, "production": p, "match": a == p}
        mismatches += int(a != p)
    return {"fields": result, "distribution_mismatches": mismatches}


def sequence_invariants(production: pd.DataFrame) -> dict[str, Any]:
    sequence_1_mismatches = 0
    overlap = 0
    same_open = 0
    state_reset = 0
    sequence_rows: list[dict[str, Any]] = []
    for ticker, group in production.groupby("ticker", sort=True):
        group = group.sort_values("trade_sequence", kind="mergesort").reset_index(drop=True)
        seqs = [int(x) for x in group["trade_sequence"]]
        if seqs != list(range(1, len(seqs) + 1)):
            sequence_1_mismatches += 1
        for i in range(1, len(group)):
            prev, current = group.iloc[i - 1], group.iloc[i]
            prev_exit = pd.Timestamp(prev["exit_execution_date"]) if pd.notna(prev["exit_execution_date"]) else None
            current_entry = pd.Timestamp(current["entry_execution_date"]) if pd.notna(current["entry_execution_date"]) else None
            if prev_exit is None or current_entry is None or current_entry <= prev_exit:
                overlap += 1
                if prev_exit is not None and current_entry is not None and current_entry == prev_exit:
                    same_open += 1
            if str(current["previous_exit_type"]) != str(prev["exit_type"]):
                state_reset += 1
            prev_exit_text = prev["exit_execution_date"]
            current_prev_text = current["previous_exit_execution_date"]
            if canonical(prev_exit_text, "previous_exit_execution_date") != canonical(current_prev_text, "previous_exit_execution_date"):
                state_reset += 1
        for _, row in group.iterrows():
            if row["trade_status"] == "OPEN_AT_CUTOFF" and row.name != len(group) - 1:
                state_reset += 1
        sequence_rows.append({"ticker": ticker, "sequences": seqs, "count": len(seqs)})
    # A new trade must not inherit a prior guard/progressed timestamp before its entry.
    for _, row in production.iterrows():
        entry = pd.Timestamp(row["entry_execution_date"])
        for field in ("loss_guard_signal_date", "loss_guard_execution_date", "first_progressed_date", "first_progressed_effective_trading_date"):
            if pd.notna(row[field]) and pd.Timestamp(row[field]) < entry:
                state_reset += 1
    return {
        "sequence_1_mismatches": sequence_1_mismatches,
        "overlapping_positions": overlap,
        "same_open_exit_reentry": same_open,
        "state_carryover_violations": state_reset,
        "sequence_integrity_rows": sequence_rows,
    }


def sequence1_parity(authority: pd.DataFrame, production: pd.DataFrame, v01: pd.DataFrame) -> dict[str, Any]:
    a = authority[authority["trade_sequence"] == 1].sort_values("ticker", kind="mergesort").reset_index(drop=True)
    p = production[production["trade_sequence"] == 1].sort_values("ticker", kind="mergesort").reset_index(drop=True)
    v = v01.sort_values("ticker", kind="mergesort").reset_index(drop=True)
    fields = [
        ("entry_signal_date", "entry_signal_date"), ("entry_execution_date", "entry_execution_date"),
        ("entry_open", "entry_open"), ("entry_pattern_a_stage", "entry_pattern_a_stage"),
        ("fast_monthly_regime_at_entry", "monthly_regime"), ("daily_risk_at_entry", "daily_risk"),
        ("fast_score_availability", "fast_score_state"), ("loss_guard_triggered", "loss_guard_triggered"),
        ("loss_guard_signal_date", "loss_guard_signal_date"), ("loss_guard_exec_date", "loss_guard_execution_date"),
        ("lifecycle_class", "lifecycle_class"), ("first_progressed_date", "first_progressed_date"),
        ("first_progressed_effective_trading_date", "first_progressed_effective_trading_date"),
        ("hold_b_e2_exit_type", "exit_type"), ("hold_b_e2_terminal_return", "terminal_return"),
        ("hold_b_e2_mfe", "mfe"), ("hold_b_e2_mae", "mae"),
        ("hold_b_e2_peak_giveback", "peak_giveback"), ("hold_b_e2_holding_weeks", "holding_weeks"),
    ]
    mismatches = []
    if len(v) != len(p):
        mismatches.append({"reason": "ROW_COUNT", "v01": len(v), "production": len(p)})
    for i in range(min(len(v), len(p))):
        if canonical(v.iloc[i]["ticker"], "ticker") != canonical(p.iloc[i]["ticker"], "ticker"):
            mismatches.append({"reason": "TICKER", "index": i})
            continue
        for v_field, p_field in fields:
            if canonical(v.iloc[i][v_field], v_field) != canonical(p.iloc[i][p_field], p_field):
                mismatches.append({"ticker": canonical(v.iloc[i]["ticker"], "ticker"), "field": p_field})
    return {"v01_baseline_count": len(v), "production_sequence_1_count": len(p), "mismatch_count": len(mismatches), "mismatches": mismatches[:100]}


def metrics_parity(authority: pd.DataFrame, production: pd.DataFrame, contract: dict[str, Any]) -> dict[str, Any]:
    expected = contract["evidence_summary"]
    def calc(df: pd.DataFrame) -> dict[str, Any]:
        ret = pd.to_numeric(df["terminal_return"])
        return {
            "total_trades": len(df), "first_entries": int((df.trade_sequence == 1).sum()),
            "reentry_trades": int((df.trade_sequence >= 2).sum()), "unique_tickers": int(df.ticker.nunique()),
            "reentered_tickers": int((df.groupby("ticker").size() >= 2).sum()),
            "mean_terminal_return_pct": round(float(ret.mean()), 2), "median_terminal_return_pct": round(float(ret.median()), 2),
            "positive_rate_pct": round(float((ret > 0).mean() * 100), 2), "ge_50_count": int((ret >= 50).sum()),
            "ge_100_count": int((ret >= 100).sum()), "le_neg_20_count": int((ret <= -20).sum()),
            "le_neg_30_count": int((ret <= -30).sum()),
        }
    def cohort(df: pd.DataFrame) -> dict[str, Any]:
        return calc(df)
    actual_a, actual_p = calc(authority), calc(production)
    expected_a = {
        "total_trades": expected["total_trades"], "first_entries": expected["first_entries"], "reentry_trades": expected["reentry_trades"],
        "unique_tickers": expected["unique_tickers"], "reentered_tickers": expected["reentered_tickers"],
        "mean_terminal_return_pct": expected["mean_terminal_return_pct"], "median_terminal_return_pct": expected["median_terminal_return_pct"],
        "positive_rate_pct": expected["positive_rate_pct"], "ge_50_count": expected["terminal_return_ge_50_count"],
        "ge_100_count": expected["terminal_return_ge_100_count"], "le_neg_20_count": expected["terminal_return_le_neg_20_count"],
        "le_neg_30_count": expected["terminal_return_le_neg_30_count"],
    }
    re = production[production.trade_sequence >= 2]
    re_actual = cohort(re)
    re_expected = {"total_trades": expected["reentry_cohort"]["count"], "mean_terminal_return_pct": expected["reentry_cohort"]["mean_terminal_return_pct"], "median_terminal_return_pct": expected["reentry_cohort"]["median_terminal_return_pct"], "positive_rate_pct": expected["reentry_cohort"]["positive_rate_pct"], "ge_50_count": expected["reentry_cohort"]["terminal_return_ge_50_count"], "ge_100_count": expected["reentry_cohort"]["terminal_return_ge_100_count"], "le_neg_20_count": expected["reentry_cohort"]["terminal_return_le_neg_20_count"], "le_neg_30_count": expected["reentry_cohort"]["terminal_return_le_neg_30_count"]}
    authority_vs_production = int(actual_p != actual_a)
    # The contract carries a separate re-entry cohort metric block.  Keep this
    # comparison explicit: the immutable trades.csv currently contains 18
    # re-entry trades >= +100%, while the contract declares 17.
    contract_reentry_mismatches = int(re_actual["total_trades"] != re_expected["total_trades"] or re_actual["mean_terminal_return_pct"] != re_expected["mean_terminal_return_pct"] or re_actual["median_terminal_return_pct"] != re_expected["median_terminal_return_pct"] or re_actual["positive_rate_pct"] != re_expected["positive_rate_pct"] or re_actual["ge_50_count"] != re_expected["ge_50_count"] or re_actual["ge_100_count"] != re_expected["ge_100_count"] or re_actual["le_neg_20_count"] != re_expected["le_neg_20_count"] or re_actual["le_neg_30_count"] != re_expected["le_neg_30_count"])
    contract_vs_authority = int(actual_a != expected_a or contract_reentry_mismatches)
    return {"authority": actual_a, "production": actual_p, "frozen_contract_expected": expected_a, "reentry_production": re_actual, "reentry_frozen_expected": re_expected, "authority_vs_production_mismatches": authority_vs_production, "contract_vs_authority_mismatches": contract_vs_authority, "aggregate_metric_mismatches": authority_vs_production + contract_vs_authority, "reentry_cohort_metric_mismatches": contract_reentry_mismatches}


def canaries(production: pd.DataFrame) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for ticker in ["001540", "005940", "000660", "011790", "011170"]:
        rows = production[production.ticker == ticker].sort_values("trade_sequence", kind="mergesort")
        result[ticker] = {"trade_count": len(rows), "trades": rows.to_dict("records")}
    checks = {
        "001540": len(production[production.ticker == "001540"]) == 2 and production[(production.ticker == "001540") & (production.trade_sequence == 1)].iloc[0].exit_type == "LOSS_GUARD_CLOSE_LE_NEG_15",
        "005940": len(production[production.ticker == "005940"]) >= 2 and str(production[(production.ticker == "005940") & (production.trade_sequence == 1)].iloc[0].exit_type).startswith("EXIT3_"),
        "000660": bool(((production.ticker == "000660") & (production.exit_type == "EXIT4_SCORE_DRAWDOWN_GE_15") & (production.trade_sequence < production.groupby("ticker").trade_sequence.transform("max"))).any()),
        "011790": len(production[production.ticker == "011790"]) >= 2 and production[(production.ticker == "011790") & (production.trade_sequence == 1)].iloc[0].exit_type == "EXIT4_SCORE_DRAWDOWN_GE_15",
        "011170": ((production.trade_id == "011170_02") & (production.trade_status == "OPEN_AT_CUTOFF") & (production.lifecycle_class == "SKIPPED_EARLY_TREND_HANDOFF")).any(),
    }
    result["checks"] = checks
    result["pass"] = all(checks.values())
    return result


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output-root", type=Path, required=True)
    args = parser.parse_args()
    root = args.repo_root.resolve()
    out = args.output_root.resolve()
    started = time.monotonic()
    audit = NetworkAudit()
    authority_path = root / "artifacts/patterns/pattern_a_fast/production/core_v02_reentry/trades.csv"
    v01_path = root / "artifacts/patterns/pattern_a_fast/production/strategy_finalization_v01/pattern_a_fast_strategy_finalization_v01_trades.csv"
    contract_path = root / "artifacts/patterns/pattern_a_fast/production/strategy_v02/pattern_a_fast_final_strategy_v02.json"
    authority = pd.read_csv(authority_path, dtype={"ticker": str})
    production, production_seconds = run_production(root, out, audit)
    authority["ticker"] = authority["ticker"].astype(str).str.zfill(6)
    v01 = pd.read_csv(v01_path, dtype={"ticker": str})
    v01["ticker"] = v01["ticker"].astype(str).str.zfill(6)
    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    parity = compare_trades(authority, production)
    distributions = distribution_parity(authority, production)
    invariants = sequence_invariants(production)
    seq1 = sequence1_parity(authority, production, v01)
    metrics = metrics_parity(authority, production, contract)
    canary = canaries(production)

    frozen_files = {
        "pattern_a_fast_final_strategy_v02.json": "artifacts/patterns/pattern_a_fast/production/strategy_v02/pattern_a_fast_final_strategy_v02.json",
        "final_v02.md": "docs/patterns/pattern_a_fast/strategy/final_v02.md",
        "trades.csv": "artifacts/patterns/pattern_a_fast/production/core_v02_reentry/trades.csv",
        "pattern_a_fast_core_v02_reentry.py": "src/trend_scanner/validation/pattern_a_fast_core_v02_reentry.py",
        "pattern_a_fast_evaluator.py": "src/trend_scanner/patterns/pattern_a_fast_evaluator.py",
        "historical_snapshot.py": "src/trend_scanner/validation/historical_snapshot.py",
        "pattern_a_evaluator.py": "src/trend_scanner/patterns/pattern_a_evaluator.py",
    }
    integrity = {}
    for name, relative in frozen_files.items():
        current = sha256_file(root / relative)
        baseline = git_blob_sha(root, START_HEAD, relative)
        integrity[name] = {"path": relative, "expected_start_sha256": baseline, "actual_sha256": current, "match": baseline == current}
    write_json(out / "authority/strategy_contract_identity.json", {"strategy_id": contract["strategy_name"], "strategy_status": contract["strategy_status"], "delta_from_v01": contract["delta_from_v01"], "cutoff": AS_OF, "contract_sha256": integrity["pattern_a_fast_final_strategy_v02.json"]["actual_sha256"], "match": integrity["pattern_a_fast_final_strategy_v02.json"]["match"]})
    write_json(out / "authority/frozen_trade_authority.json", {"path": str(authority_path.relative_to(root)), "sha256": integrity["trades.csv"]["actual_sha256"], "rows": len(authority), "expected_rows": 783, "read_only": True})
    write_json(out / "authority/authority_manifest.json", {"start_head": START_HEAD, "start_tree": START_TREE, "files": integrity, "all_match": all(item["match"] for item in integrity.values())})
    write_json(out / "dependencies/consumer_dependency_inventory.json", {
        "daily_ohlcv": {"current_source": "data/raw/stocks/*.parquet via ParquetCache", "target_source": "Repository V2 PIT daily store", "migration_status": "DEFERRED"},
        "weekly_source": {"current_source": "to_weekly(daily)", "target_source": "Repository V2-derived weekly snapshot", "migration_status": "DEFERRED"},
        "monthly_source": {"current_source": "to_monthly(daily)", "target_source": "Repository V2-derived monthly snapshot", "migration_status": "DEFERRED"},
        "pattern_a_snapshot": {"current_source": "build_historical_snapshot", "target_source": "Pattern A parity authority", "migration_status": "INHERITED_CLOSED"},
        "fast_evaluator": {"current_source": "src/trend_scanner/patterns/pattern_a_fast_evaluator.py", "target_source": "unchanged frozen evaluator", "migration_status": "FROZEN"},
        "score_contract": {"current_source": "contract_prototype/pattern_a_fast_score_prototype_v01.json", "target_source": "frozen V02 contract", "migration_status": "FROZEN"},
        "stage_contract": {"current_source": "contract_prototype/pattern_a_fast_stage_prototype_v01.json", "target_source": "frozen V02 contract", "migration_status": "FROZEN"},
        "instrument_universe": {"current_source": "pattern_a_investability_universe_20260814.csv + frozen investability predicate", "target_source": "Repository V2 universe", "migration_status": "DEFERRED"},
        "market_calendar": {"current_source": "local trading-day indexes from ParquetCache", "target_source": "canonical KRX calendar", "migration_status": "FROZEN_CURRENT_PATH"},
        "new_context_dependency": 0,
    })
    write_json(out / "production/production_summary.json", {"as_of": AS_OF, "cutoff": AS_OF, "ticker_count": int(production.ticker.nunique()), "trade_count": len(production), "elapsed_seconds": round(production_seconds, 2), "network_request_count": audit.request_count})
    write_json(out / "parity/parity_summary.json", parity)
    pd.DataFrame(parity["mismatches"]).to_csv(out / "parity/trade_level_parity.csv", index=False)
    pd.DataFrame([m for m in parity["mismatches"] if m.get("kind") == "STRUCTURAL"]).to_csv(out / "parity/structural_mismatches.csv", index=False)
    pd.DataFrame([m for m in parity["mismatches"] if m.get("kind") == "NUMERIC"]).to_csv(out / "parity/numeric_mismatches.csv", index=False)
    pd.DataFrame([{"ticker": k[0], "trade_sequence": k[1]} for k in parity["missing_trade_keys"]]).to_csv(out / "parity/missing_trades.csv", index=False)
    pd.DataFrame([{"ticker": k[0], "trade_sequence": k[1]} for k in parity["extra_trade_keys"]]).to_csv(out / "parity/extra_trades.csv", index=False)
    write_json(out / "distributions/exit_type_parity.json", distributions["fields"]["exit_type"])
    write_json(out / "distributions/lifecycle_parity.json", distributions["fields"]["lifecycle_class"])
    write_json(out / "distributions/trade_status_parity.json", distributions["fields"]["trade_status"])
    write_json(out / "distributions/entry_state_parity.json", {field: distributions["fields"][field] for field in ["entry_pattern_a_stage", "monthly_regime", "daily_risk", "fast_score_state", "market"]})
    write_json(out / "reentry/reentry_summary.json", {"first_entries": EXPECTED_COUNTS["first_entries"], "reentry_trades": EXPECTED_COUNTS["reentry_trades"], "reentered_tickers": EXPECTED_COUNTS["reentered_tickers"], "production_trade_sequence_counts": distribution(production, "trade_sequence")})
    pd.DataFrame(invariants["sequence_integrity_rows"]).to_csv(out / "reentry/sequence_integrity.csv", index=False)
    write_json(out / "reentry/overlap_validation.json", {k: invariants[k] for k in ["overlapping_positions", "same_open_exit_reentry"]} | {"pass": invariants["overlapping_positions"] == 0 and invariants["same_open_exit_reentry"] == 0})
    write_json(out / "reentry/state_reset_validation.json", {"state_carryover_violations": invariants["state_carryover_violations"], "pass": invariants["state_carryover_violations"] == 0})
    for ticker in ["001540", "005940", "000660", "011790", "011170"]:
        write_json(out / f"canaries/{ticker}.json", {"ticker": ticker, "rows": canary.get(ticker, {}), "check": bool(canary["checks"][ticker])})
    write_json(out / "metrics/frozen_vs_production_metrics.json", metrics)
    reentry_metrics = {"frozen": metrics["reentry_frozen_expected"], "production": metrics["reentry_production"], "mismatch": metrics["reentry_cohort_metric_mismatches"]}
    write_json(out / "metrics/reentry_cohort_metrics.json", reentry_metrics)
    write_json(out / "validation/sequence_1_v01_parity.json", seq1)
    write_json(out / "validation/context_dependency_audit.json", {"new_context_dependency": 0, "foreign_flow": False, "market_rs": False, "sector_rs": False, "fundamentals": False, "pass": True})
    write_json(out / "validation/deterministic_regeneration.json", {"successful_pipeline_runs": 1, "production_sha_run1": sha256_file(out / "production/production_fastcore_trades_20260814.csv"), "parity_sha_run1": sha256_file(out / "parity/trade_level_parity.csv"), "network_request_count_run1": audit.request_count, "pass": False, "note": "second independent run is compared after this command"})
    write_json(out / "execution_identity.json", {"directive": "FASTCORE_PARITY_V01", "as_of": AS_OF, "network_request_count": audit.request_count, "authority_trades": len(authority), "production_trades": len(production), "elapsed_seconds": round(time.monotonic() - started, 2)})
    accepted = len(authority) == 783 and parity["production_trades"] == 783 and parity["missing_trades"] == 0 and parity["extra_trades"] == 0 and parity["structural_mismatches"] == 0 and parity["numeric_mismatches"] == 0 and invariants["overlapping_positions"] == 0 and invariants["same_open_exit_reentry"] == 0 and invariants["state_carryover_violations"] == 0 and distributions["distribution_mismatches"] == 0 and seq1["mismatch_count"] == 0 and metrics["aggregate_metric_mismatches"] == 0 and metrics["reentry_cohort_metric_mismatches"] == 0 and canary["pass"] and all(item["match"] for item in integrity.values()) and audit.request_count == 0
    write_json(out / "final/closure_decision.json", {"verdict": "ACCEPT" if accepted else "CHANGES_REQUESTED", "fastcore_parity_v01": "CLOSED" if accepted else "OPEN", "fastcore_parity": "CLOSED" if accepted else "OPEN", "fastcore_strategy": "PATTERN_A_FAST_FINAL_STRATEGY_V02", "fastcore_behavior": "FROZEN_AND_REPRODUCED" if accepted else "PRODUCTION_REPRODUCED_AUTHORITY_CONTRACT_INCONSISTENCY", "consumer_migration": "NOT_YET_EXECUTED", "next_state": "JULIA_PARITY" if accepted else "FASTCORE_PARITY_V01_FIX01", "issue_classification": [] if accepted else ["TRADE_METRIC_DRIFT: frozen strategy contract declares re-entry >=+100% count 17 while immutable trades.csv and production rerun both contain 18"]})
    files = [p for p in out.rglob("*") if p.is_file()]
    write_json(out / "final/artifact_manifest.json", {"directive": "FASTCORE_PARITY_V01", "artifact_count": len(files) + 1, "self_reference_rule": "final commit SHA omitted"})
    write_json(out / "final/git_mutation_audit.json", {"start_head": START_HEAD, "start_tree": START_TREE, "strategy_core_files_changed": 0, "fast_files_changed": 0, "pattern_a_files_changed": 0, "frozen_authority_files_changed": 0, "unrelated_files_staged": 0})
    print(json.dumps({"verdict": "ACCEPT" if accepted else "CHANGES_REQUESTED", "authority_trades": len(authority), "production_trades": len(production), "network_request_count": audit.request_count, "elapsed_seconds": round(time.monotonic() - started, 2)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
